package attendance;

public enum ReportType {
    COMPREHENSIVE,
    ATTENDANCE_CALENDAR_SEMESTER,
    TASK_LIST_ALL,
    TASK_LIST_PENDING,
    TASK_LIST_COMPLETED,
    TASK_LIST_INCOMPLETE,
    CGPA_SEMESTER,
    CGPA_OVERALL,
    DAILY_BUY,
    REGISTRATION_FEE_SEMESTER,
    REGISTRATION_FEE_OVERALL,
    COURSE_LIST,
    EXPENSE_REPORT,
    ACTION_LOG,
    NAVIGATION_FLOW,
    FUND_REPORT,
    DATA_JSON_VIEW
}
